name: tipitaka
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^2.3.12
  stacked_services: ^0.8.26
  #stacked_hooks: ^0.2.2
  get_it: ^7.2.0
  flutter_hooks: ^0.18.3
  observable_ish: ^4.0.6  
  shared_preferences: ^2.0.12
  stacked_themes: ^0.3.9
  audioplayers: ^0.20.1
  path_provider: ^2.0.10
  file_picker: ^4.5.1
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/icon.jpg"

flutter:

  uses-material-design: true
  assets:
    - assets/
